# Generated by Django 4.2.1 on 2023-06-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duan',
            name='fkduongpho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.duongpho'),
        ),
        migrations.AddField(
            model_name='duongpho',
            name='fkxaphuong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.xaphuong'),
        ),
        migrations.AddField(
            model_name='xaphuong',
            name='fkquanhuyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.quanhuyen'),
        ),
    ]
